### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by TransparentMan** [butor/blackbird#58]
/root/blackbird-master/src/bitfinex.cpp:138: undefined reference to `base64_encode[abi:cxx11](unsigned char const*, unsigned int)'
collect2: error: ld returned 1 exit status

I get this error when trying to build a program after I updated Ubuntu to 16.04
